apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xmzm
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0050-tenant/tkrw-pr712-0075-0050-app/devfile-sample-xmzm@sha256:75610fa6c64d80c3c8a2b1bafbb15a2ba1cd25759d81907f03594bf784cd445c
        name: my-nodejs
        resources: {}
status: {}
